pipeline:
  name: harness-poc-bg-normal
  identifier: harnesspocbgnormal
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: hellotest1
          environment:
            environmentRef: preprod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnesspocbg
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    skipUnchangedManifest: false
                    delegateSelectors:
                      - harness-delegate
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Verification
                        action:
                          type: PipelineRollback
              - step:
                  type: Verify
                  name: Verify_1
                  identifier: Verify_1
                  spec:
                    isMultiServicesOrEnvs: false
                    type: Bluegreen
                    monitoredService:
                      type: Default
                      spec: {}
                    spec:
                      sensitivity: HIGH
                      duration: 5m
                      deploymentTag: <+artifacts.primary.tag>
                  timeout: 2h
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Verification
                        action:
                          type: PipelineRollback
                    - onFailure:
                        errors:
                          - Unknown
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: Ignore
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
