apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "WebApp.fullname" . }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "WebApp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "WebApp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: {{ include "WebApp.fullname" . }}
